<a href="https://colab.research.google.com/github/KirolosKhairy/Data-Analysis/blob/main/%D0%94%D0%97_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##🧭 Часть 1 — Polars: Titanic (train.csv) — Загрузка и первичный анализ

###🔧 Подготовка окружения (Colab)

In [1]:
!pip -q install polars pyarrow
import polars as pl
pl.Config.set_tbl_rows(30)
pl.Config.set_tbl_width_chars(160)
pl.Config.set_fmt_str_lengths(80)

polars.config.Config

###📥 Чтение датасета из /content/train.csv

In [2]:
import polars as pl
dtypes = {"PassengerId": pl.Int32, "Survived": pl.Int8, "Pclass": pl.Int8, "Name": pl.Utf8, "Sex": pl.Categorical, "Age": pl.Float32, "SibSp": pl.Int8, "Parch": pl.Int8, "Ticket": pl.Utf8, "Fare": pl.Float32, "Cabin": pl.Utf8, "Embarked": pl.Categorical}
try:
    df = pl.read_csv("/content/train.csv", dtypes=dtypes)
except:
    df = pl.read_csv("/content/train.csv")
df

/tmp/ipython-input-674624238.py:4: DeprecationWarning: The argument `dtypes` for `read_csv` is deprecated. It has been renamed to `schema_overrides`.
  df = pl.read_csv("/content/train.csv", dtypes=dtypes)

shape: (891, 12)
┌─────────────┬──────────┬────────┬─────────────────────────────────────────────────────┬───┬──────────────────┬───────────┬───────┬──────────┐
│ PassengerId ┆ Survived ┆ Pclass ┆ Name                                                ┆ … ┆ Ticket           ┆ Fare      ┆ Cabin ┆ Embarked │
│ ---         ┆ ---      ┆ ---    ┆ ---                                                 ┆   ┆ ---              ┆ ---       ┆ ---   ┆ ---      │
│ i32         ┆ i8       ┆ i8     ┆ str                                                 ┆   ┆ str              ┆ f32       ┆ str   ┆ cat      │
╞═════════════╪══════════╪════════╪═════════════════════════════════════════════════════╪═══╪══════════════════╪═══════════╪═══════╪══════════╡
│ 1           ┆ 0        ┆ 3      ┆ Braund, Mr. Owen Harris                             ┆ … ┆ A/5 21171        ┆ 7.25      ┆ null  ┆ S        │
│ 2           ┆ 1        ┆ 1      ┆ Cumings, Mrs. John Bradley (Florence Briggs Thayer) ┆ … ┆ PC 17599         ┆ 71.283302 ┆ C85   ┆ C        │
│ 3           ┆ 1        ┆ 3      ┆ Heikkinen, Miss. Laina                              ┆ … ┆ STON/O2. 3101282 ┆ 7.925     ┆ null  ┆ S        │
│ 4           ┆ 1        ┆ 1      ┆ Futrelle, Mrs. Jacques Heath (Lily May Peel)        ┆ … ┆ 113803           ┆ 53.099998 ┆ C123  ┆ S        │
│ 5           ┆ 0        ┆ 3      ┆ Allen, Mr. William Henry                            ┆ … ┆ 373450           ┆ 8.05      ┆ null  ┆ S        │
│ 6           ┆ 0        ┆ 3      ┆ Moran, Mr. James                                    ┆ … ┆ 330877           ┆ 8.4583    ┆ null  ┆ Q        │
│ 7           ┆ 0        ┆ 1      ┆ McCarthy, Mr. Timothy J                             ┆ … ┆ 17463            ┆ 51.862499 ┆ E46   ┆ S        │
│ 8           ┆ 0        ┆ 3      ┆ Palsson, Master. Gosta Leonard                      ┆ … ┆ 349909           ┆ 21.075001 ┆ null  ┆ S        │
│ 9           ┆ 1        ┆ 3      ┆ Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)   ┆ … ┆ 347742           ┆ 11.1333   ┆ null  ┆ S        │
│ 10          ┆ 1        ┆ 2      ┆ Nasser, Mrs. Nicholas (Adele Achem)                 ┆ … ┆ 237736           ┆ 30.070801 ┆ null  ┆ C        │
│ 11          ┆ 1        ┆ 3      ┆ Sandstrom, Miss. Marguerite Rut                     ┆ … ┆ PP 9549          ┆ 16.700001 ┆ G6    ┆ S        │
│ 12          ┆ 1        ┆ 1      ┆ Bonnell, Miss. Elizabeth                            ┆ … ┆ 113783           ┆ 26.549999 ┆ C103  ┆ S        │
│ 13          ┆ 0        ┆ 3      ┆ Saundercock, Mr. William Henry                      ┆ … ┆ A/5. 2151        ┆ 8.05      ┆ null  ┆ S        │
│ 14          ┆ 0        ┆ 3      ┆ Andersson, Mr. Anders Johan                         ┆ … ┆ 347082           ┆ 31.275    ┆ null  ┆ S        │
│ 15          ┆ 0        ┆ 3      ┆ Vestrom, Miss. Hulda Amanda Adolfina                ┆ … ┆ 350406           ┆ 7.8542    ┆ null  ┆ S        │
│ …           ┆ …        ┆ …      ┆ …                                                   ┆ … ┆ …                ┆ …         ┆ …     ┆ …        │
│ 877         ┆ 0        ┆ 3      ┆ Gustafsson, Mr. Alfred Ossian                       ┆ … ┆ 7534             ┆ 9.8458    ┆ null  ┆ S        │
│ 878         ┆ 0        ┆ 3      ┆ Petroff, Mr. Nedelio                                ┆ … ┆ 349212           ┆ 7.8958    ┆ null  ┆ S        │
│ 879         ┆ 0        ┆ 3      ┆ Laleff, Mr. Kristo                                  ┆ … ┆ 349217           ┆ 7.8958    ┆ null  ┆ S        │
│ 880         ┆ 1        ┆ 1      ┆ Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)       ┆ … ┆ 11767            ┆ 83.158302 ┆ C50   ┆ C        │
│ 881         ┆ 1        ┆ 2      ┆ Shelley, Mrs. William (Imanita Parrish Hall)        ┆ … ┆ 230433           ┆ 26.0      ┆ null  ┆ S        │
│ 882         ┆ 0        ┆ 3      ┆ Markun, Mr. Johann                                  ┆ … ┆ 349257           ┆ 7.8958    ┆ null  ┆ S        │
│ 883         ┆ 0        ┆ 3      ┆ Dahlberg, Miss. Gerda Ulrika                        ┆ … ┆ 7552             ┆ 10.5167   ┆ null  ┆ S        │
│ 884         ┆ 0        ┆ 2      ┆ Banfield, Mr. Frederick James                       ┆ … ┆ C.A./SOTON 34068 ┆ 10.5      ┆ null  ┆ S        │
│ 885         ┆ 0        ┆ 3      ┆ Sutehall, Mr. Henry Jr                              ┆ … ┆ SOTON/OQ 392076  ┆ 7.05      ┆ null  ┆ S        │
│ 886         ┆ 0        ┆ 3      ┆ Rice, Mrs. William (Margaret Norton)                ┆ … ┆ 382652           ┆ 29.125    ┆ null  ┆ Q        │
│ 887         ┆ 0        ┆ 2      ┆ Montvila, Rev. Juozas                               ┆ … ┆ 211536           ┆ 13.0      ┆ null  ┆ S        │
│ 888         ┆ 1        ┆ 1      ┆ Graham, Miss. Margaret Edith                        ┆ … ┆ 112053           ┆ 30.0      ┆ B42   ┆ S        │
│ 889         ┆ 0        ┆ 3      ┆ Johnston, Miss. Catherine Helen "Carrie"            ┆ … ┆ W./C. 6607       ┆ 23.450001 ┆ null  ┆ S        │
│ 890         ┆ 1        ┆ 1      ┆ Behr, Mr. Karl Howell                               ┆ … ┆ 111369           ┆ 30.0      ┆ C148  ┆ C        │
│ 891         ┆ 0        ┆ 3      ┆ Dooley, Mr. Patrick                                 ┆ … ┆ 370376           ┆ 7.75      ┆ null  ┆ Q        │
└─────────────┴──────────┴────────┴─────────────────────────────────────────────────────┴───┴──────────────────┴───────────┴───────┴──────────┘

###🧮 Размеры датасета

In [3]:
pl.DataFrame({"metric": ["rows","cols"], "value": [df.height, df.width]})

shape: (2, 2)
┌────────┬───────┐
│ metric ┆ value │
│ ---    ┆ ---   │
│ str    ┆ i64   │
╞════════╪═══════╡
│ rows   ┆ 891   │
│ cols   ┆ 12    │
└────────┴───────┘

###🧩 Типы столбцов

In [4]:
pl.DataFrame({"column": df.columns, "dtype": [str(t) for t in df.dtypes]})

shape: (12, 2)
┌─────────────┬──────────────────────────────────┐
│ column      ┆ dtype                            │
│ ---         ┆ ---                              │
│ str         ┆ str                              │
╞═════════════╪══════════════════════════════════╡
│ PassengerId ┆ Int32                            │
│ Survived    ┆ Int8                             │
│ Pclass      ┆ Int8                             │
│ Name        ┆ String                           │
│ Sex         ┆ Categorical(ordering='physical') │
│ Age         ┆ Float32                          │
│ SibSp       ┆ Int8                             │
│ Parch       ┆ Int8                             │
│ Ticket      ┆ String                           │
│ Fare        ┆ Float32                          │
│ Cabin       ┆ String                           │
│ Embarked    ┆ Categorical(ordering='physical') │
└─────────────┴──────────────────────────────────┘

###🚫 Пропуски по столбцам

In [5]:
df.null_count().transpose(include_header=True, header_name="column", column_names=["nulls"]).sort("nulls", descending=True)

shape: (12, 2)
┌─────────────┬───────┐
│ column      ┆ nulls │
│ ---         ┆ ---   │
│ str         ┆ u32   │
╞═════════════╪═══════╡
│ Cabin       ┆ 687   │
│ Age         ┆ 177   │
│ Embarked    ┆ 2     │
│ PassengerId ┆ 0     │
│ Survived    ┆ 0     │
│ Pclass      ┆ 0     │
│ Name        ┆ 0     │
│ Sex         ┆ 0     │
│ SibSp       ┆ 0     │
│ Parch       ┆ 0     │
│ Ticket      ┆ 0     │
│ Fare        ┆ 0     │
└─────────────┴───────┘

###📊 Описательная статистика

In [6]:
df.describe()

shape: (9, 13)
┌────────────┬─────────────┬──────────┬──────────┬───┬───────────┬────────────┬───────┬──────────┐
│ statistic  ┆ PassengerId ┆ Survived ┆ Pclass   ┆ … ┆ Ticket    ┆ Fare       ┆ Cabin ┆ Embarked │
│ ---        ┆ ---         ┆ ---      ┆ ---      ┆   ┆ ---       ┆ ---        ┆ ---   ┆ ---      │
│ str        ┆ f64         ┆ f64      ┆ f64      ┆   ┆ str       ┆ f64        ┆ str   ┆ str      │
╞════════════╪═════════════╪══════════╪══════════╪═══╪═══════════╪════════════╪═══════╪══════════╡
│ count      ┆ 891.0       ┆ 891.0    ┆ 891.0    ┆ … ┆ 891       ┆ 891.0      ┆ 204   ┆ 889      │
│ null_count ┆ 0.0         ┆ 0.0      ┆ 0.0      ┆ … ┆ 0         ┆ 0.0        ┆ 687   ┆ 2        │
│ mean       ┆ 446.0       ┆ 0.383838 ┆ 2.308642 ┆ … ┆ null      ┆ 32.204208  ┆ null  ┆ null     │
│ std        ┆ 257.353842  ┆ 0.486592 ┆ 0.836071 ┆ … ┆ null      ┆ 49.693428  ┆ null  ┆ null     │
│ min        ┆ 1.0         ┆ 0.0      ┆ 1.0      ┆ … ┆ 110152    ┆ 0.0        ┆ A10   ┆ null     │
│ 25%        ┆ 224.0       ┆ 0.0      ┆ 2.0      ┆ … ┆ null      ┆ 7.925      ┆ null  ┆ null     │
│ 50%        ┆ 446.0       ┆ 0.0      ┆ 3.0      ┆ … ┆ null      ┆ 14.4542    ┆ null  ┆ null     │
│ 75%        ┆ 669.0       ┆ 1.0      ┆ 3.0      ┆ … ┆ null      ┆ 31.0       ┆ null  ┆ null     │
│ max        ┆ 891.0       ┆ 1.0      ┆ 3.0      ┆ … ┆ WE/P 5735 ┆ 512.329224 ┆ T     ┆ null     │
└────────────┴─────────────┴──────────┴──────────┴───┴───────────┴────────────┴───────┴──────────┘

###🎟️ Количество пассажиров по классам (Pclass)

In [7]:
df.group_by("Pclass").agg(pl.len().alias("count")).sort("Pclass")

shape: (3, 2)
┌────────┬───────┐
│ Pclass ┆ count │
│ ---    ┆ ---   │
│ i8     ┆ u32   │
╞════════╪═══════╡
│ 1      ┆ 216   │
│ 2      ┆ 184   │
│ 3      ┆ 491   │
└────────┴───────┘

###🛟 Количество выживших по полу (Sex)

In [8]:
df.filter(pl.col("Survived") == 1).group_by("Sex").agg(pl.len().alias("count")).sort("Sex")

shape: (2, 2)
┌────────┬───────┐
│ Sex    ┆ count │
│ ---    ┆ ---   │
│ cat    ┆ u32   │
╞════════╪═══════╡
│ male   ┆ 109   │
│ female ┆ 233   │
└────────┴───────┘

###👴 Пассажиры старше 44 лет

In [9]:
df.filter(pl.col("Age") > 44).select(["PassengerId","Name","Sex","Age","Pclass","Survived","Fare"]).sort("Age", descending=True)

shape: (115, 7)
┌─────────────┬─────────────────────────────────────────────────┬────────┬──────┬────────┬──────────┬────────────┐
│ PassengerId ┆ Name                                            ┆ Sex    ┆ Age  ┆ Pclass ┆ Survived ┆ Fare       │
│ ---         ┆ ---                                             ┆ ---    ┆ ---  ┆ ---    ┆ ---      ┆ ---        │
│ i32         ┆ str                                             ┆ cat    ┆ f32  ┆ i8     ┆ i8       ┆ f32        │
╞═════════════╪═════════════════════════════════════════════════╪════════╪══════╪════════╪══════════╪════════════╡
│ 631         ┆ Barkworth, Mr. Algernon Henry Wilson            ┆ male   ┆ 80.0 ┆ 1      ┆ 1        ┆ 30.0       │
│ 852         ┆ Svensson, Mr. Johan                             ┆ male   ┆ 74.0 ┆ 3      ┆ 0        ┆ 7.775      │
│ 97          ┆ Goldschmidt, Mr. George B                       ┆ male   ┆ 71.0 ┆ 1      ┆ 0        ┆ 34.654202  │
│ 494         ┆ Artagaveytia, Mr. Ramon                         ┆ male   ┆ 71.0 ┆ 1      ┆ 0        ┆ 49.5042    │
│ 117         ┆ Connors, Mr. Patrick                            ┆ male   ┆ 70.5 ┆ 3      ┆ 0        ┆ 7.75       │
│ 673         ┆ Mitchell, Mr. Henry Michael                     ┆ male   ┆ 70.0 ┆ 2      ┆ 0        ┆ 10.5       │
│ 746         ┆ Crosby, Capt. Edward Gifford                    ┆ male   ┆ 70.0 ┆ 1      ┆ 0        ┆ 71.0       │
│ 34          ┆ Wheadon, Mr. Edward H                           ┆ male   ┆ 66.0 ┆ 2      ┆ 0        ┆ 10.5       │
│ 55          ┆ Ostby, Mr. Engelhart Cornelius                  ┆ male   ┆ 65.0 ┆ 1      ┆ 0        ┆ 61.979198  │
│ 281         ┆ Duane, Mr. Frank                                ┆ male   ┆ 65.0 ┆ 3      ┆ 0        ┆ 7.75       │
│ 457         ┆ Millet, Mr. Francis Davis                       ┆ male   ┆ 65.0 ┆ 1      ┆ 0        ┆ 26.549999  │
│ 439         ┆ Fortune, Mr. Mark                               ┆ male   ┆ 64.0 ┆ 1      ┆ 0        ┆ 263.0      │
│ 546         ┆ Nicholson, Mr. Arthur Ernest                    ┆ male   ┆ 64.0 ┆ 1      ┆ 0        ┆ 26.0       │
│ 276         ┆ Andrews, Miss. Kornelia Theodosia               ┆ female ┆ 63.0 ┆ 1      ┆ 1        ┆ 77.958298  │
│ 484         ┆ Turkula, Mrs. (Hedwig)                          ┆ female ┆ 63.0 ┆ 3      ┆ 1        ┆ 9.5875     │
│ …           ┆ …                                               ┆ …      ┆ …    ┆ …      ┆ …        ┆ …          │
│ 790         ┆ Guggenheim, Mr. Benjamin                        ┆ male   ┆ 46.0 ┆ 1      ┆ 0        ┆ 79.199997  │
│ 204         ┆ Youseff, Mr. Gerious                            ┆ male   ┆ 45.5 ┆ 3      ┆ 0        ┆ 7.225      │
│ 332         ┆ Partner, Mr. Austen                             ┆ male   ┆ 45.5 ┆ 1      ┆ 0        ┆ 28.5       │
│ 63          ┆ Harris, Mr. Henry Birkhardt                     ┆ male   ┆ 45.0 ┆ 1      ┆ 0        ┆ 83.474998  │
│ 130         ┆ Ekstrom, Mr. Johan                              ┆ male   ┆ 45.0 ┆ 3      ┆ 0        ┆ 6.975      │
│ 168         ┆ Skoog, Mrs. William (Anna Bernhardina Karlsson) ┆ female ┆ 45.0 ┆ 3      ┆ 0        ┆ 27.9       │
│ 188         ┆ Romaine, Mr. Charles Hallace ("Mr C Rolmane")   ┆ male   ┆ 45.0 ┆ 1      ┆ 1        ┆ 26.549999  │
│ 277         ┆ Lindblom, Miss. Augusta Charlotta               ┆ female ┆ 45.0 ┆ 3      ┆ 0        ┆ 7.75       │
│ 339         ┆ Dahl, Mr. Karl Edwart                           ┆ male   ┆ 45.0 ┆ 3      ┆ 1        ┆ 8.05       │
│ 340         ┆ Blackwell, Mr. Stephen Weart                    ┆ male   ┆ 45.0 ┆ 1      ┆ 0        ┆ 35.5       │
│ 363         ┆ Barbara, Mrs. (Catherine David)                 ┆ female ┆ 45.0 ┆ 3      ┆ 0        ┆ 14.4542    │
│ 441         ┆ Hart, Mrs. Benjamin (Esther Ada Bloomfield)     ┆ female ┆ 45.0 ┆ 2      ┆ 1        ┆ 26.25      │
│ 537         ┆ Butt, Major. Archibald Willingham               ┆ male   ┆ 45.0 ┆ 1      ┆ 0        ┆ 26.549999  │
│ 707         ┆ Kelly, Mrs. Florence "Fannie"                   ┆ female ┆ 45.0 ┆ 2      ┆ 1        ┆ 13.5       │
│ 857         ┆ Wick, Mrs. George Dennick (Mary Hitchcock)      ┆ female ┆ 45.0 ┆ 1      ┆ 1        ┆ 164.866699 │
└─────────────┴─────────────────────────────────────────────────┴────────┴──────┴────────┴──────────┴────────────┘

In [10]:
import polars as pl
df_gt44 = df.filter(pl.col("Age") > 44)
pl.DataFrame({
    "rows":[df_gt44.height],
    "cols":[df_gt44.width],
    "all_age_gt_44":[df_gt44.select((pl.col("Age") > 44).all()).to_series().item()],
    "nulls_in_age":[df_gt44.select(pl.col("Age").null_count()).to_series().item()],
    "min_age":[df_gt44.select(pl.col("Age").min()).to_series().item()],
    "max_age":[df_gt44.select(pl.col("Age").max()).to_series().item()]
})

shape: (1, 6)
┌──────┬──────┬───────────────┬──────────────┬─────────┬─────────┐
│ rows ┆ cols ┆ all_age_gt_44 ┆ nulls_in_age ┆ min_age ┆ max_age │
│ ---  ┆ ---  ┆ ---           ┆ ---          ┆ ---     ┆ ---     │
│ i64  ┆ i64  ┆ bool          ┆ i64          ┆ f64     ┆ f64     │
╞══════╪══════╪═══════════════╪══════════════╪═════════╪═════════╡
│ 115  ┆ 12   ┆ true          ┆ 0            ┆ 45.0    ┆ 80.0    │
└──────┴──────┴───────────────┴──────────────┴─────────┴─────────┘

##🏎️ Часть 2 — Ускорение работы с pandas (Titanic: /content/train.csv)

###🔧 Установка и импорт

In [11]:
!pip -q install bottleneck
import pandas as pd
import numpy as np
import bottleneck as bn

###📥 Чтение датасета из /content/train.csv

In [12]:
df_pd = pd.read_csv("/content/train.csv")
df_pd.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

###📐 Средний возраст и σ с bottleneck

In [13]:
age = pd.to_numeric(df_pd["Age"], errors="coerce").to_numpy(dtype=float)
age_mean = bn.nanmean(age)
age_std = bn.nanstd(age)
pd.DataFrame({"metric":["mean_age","std_age"],"value":[age_mean, age_std]})

     metric      value
0  mean_age  29.699118
1   std_age  14.516321

###💸 Векторное преобразование Fare → Fare_new

In [14]:
mult = np.where(df_pd["Pclass"].isin([1,2]), 1.3, 1.1)
df_pd["Fare_new"] = df_pd["Fare"].astype(float) * mult
df_pd[["Pclass","Fare","Fare_new"]].head(10)

   Pclass     Fare  Fare_new
0       3   7.2500   7.97500
1       1  71.2833  92.66829
2       3   7.9250   8.71750
3       1  53.1000  69.03000
4       3   8.0500   8.85500
5       3   8.4583   9.30413
6       1  51.8625  67.42125
7       3  21.0750  23.18250
8       3  11.1333  12.24663
9       2  30.0708  39.09204

###✅ Мини-проверки результата

In [15]:
df_pd["Pclass"].value_counts().sort_index()

Pclass
1    216
2    184
3    491
Name: count, dtype: int64

In [16]:
df_pd["Fare_new"].isna().sum()

np.int64(0)

In [17]:
df_pd[["Fare","Fare_new"]].describe()

             Fare    Fare_new
count  891.000000  891.000000
mean    32.204208   40.358244
std     49.693429   64.894005
min      0.000000    0.000000
25%      7.910400    8.701440
50%     14.454200   16.900000
75%     31.000000   39.000000
max    512.329200  666.027960

##🧠 Часть 3 — Оптимизация типов в pandas (Housing.csv)

🔧 Установка и импорт

In [18]:
import pandas as pd
import numpy as np

###📥 Чтение датасета

In [19]:
df = pd.read_csv("/content/Housing.csv")
df.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished

###📦 Базовое потребление памяти

In [20]:
base_mem_bytes = df.memory_usage(deep=True).sum()
base_mem_mb = base_mem_bytes / (1024**2)
pd.DataFrame({"metric":["memory_before_mb"],"value":[base_mem_mb]})

             metric     value
0  memory_before_mb  0.216717

###🧭 Автоподбор оптимальных типов

In [21]:
from pandas.api.types import is_integer_dtype, is_float_dtype, is_bool_dtype, is_object_dtype

def suggest_dtype(s):
    name = s.name
    non_null = s.notna().sum()
    nunique = s.nunique(dropna=True)
    pct_unique = (nunique / non_null) if non_null else np.nan
    orig = str(s.dtype)
    sugg = orig
    reason = "keep"
    if is_integer_dtype(s):
        s2 = pd.to_numeric(s, downcast="integer")
        sugg = str(s2.dtype)
        reason = "downcast_integer"
    elif is_float_dtype(s):
        s2 = pd.to_numeric(s, downcast="float")
        sugg = str(s2.dtype)
        reason = "downcast_float"
    elif is_bool_dtype(s):
        if s.isna().any():
            sugg = "boolean"
        else:
            sugg = "bool"
        reason = "bool"
    elif is_object_dtype(s):
        s_dt = pd.to_datetime(s, errors="coerce", infer_datetime_format=True)
        ok = s_dt.notna().sum()
        if non_null and ok / non_null >= 0.95 and ok > 0:
            sugg = "datetime64[ns]"
            reason = "datetime"
        else:
            vals = s.dropna().astype(str).str.lower().str.strip()
            m_true = {"true","yes","y","1"}
            m_false = {"false","no","n","0"}
            is_boolish = vals.isin(m_true.union(m_false))
            if non_null and is_boolish.mean() >= 0.95:
                sugg = "boolean"
                reason = "bool_from_text"
            else:
                if non_null and nunique > 0 and (nunique <= max(50, int(0.5*non_null))):
                    sugg = "category"
                    reason = "low_cardinality"
                else:
                    sugg = "object"
                    reason = "text"
    return orig, sugg, non_null, nunique, pct_unique, reason

profile = []
for c in df.columns:
    orig, sugg, non_null, nunique, pct_unique, reason = suggest_dtype(df[c])
    profile.append([c, orig, sugg, non_null, nunique, pct_unique, reason])

report = pd.DataFrame(profile, columns=["column","orig_dtype","suggested_dtype","non_null","n_unique","pct_unique","reason"])
report

/tmp/ipython-input-869338356.py:26: UserWarning: The argument 'infer_datetime_format' is deprecated and will be removed in a future version. A strict version of it is now the default, see https://pandas.pydata.org/pdeps/0004-consistent-to-datetime-parsing.html. You can safely remove this argument.
  s_dt = pd.to_datetime(s, errors="coerce", infer_datetime_format=True)
/tmp/ipython-input-869338356.py:26: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  s_dt = pd.to_datetime(s, errors="coerce", infer_datetime_format=True)
/tmp/ipython-input-869338356.py:26: UserWarning: The argument 'infer_datetime_format' is deprecated and will be removed in a future version. A strict version of it is now the default, see https://pandas.pydata.org/pdeps/0004-consistent-to-datetime-parsing.html. You can safely remove this argument.
  s_dt = pd.to_datetime(s, errors="coerce", infer_datetime_format=True)
/tmp/ipython-input-869338356.py:26: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  s_dt = pd.to_datetime(s, errors="coerce", infer_datetime_format=True)
/tmp/ipython-input-869338356.py:26: UserWarning: The argument 'infer_datetime_format' is deprecated and will be removed in a future version. A strict version of it is now the default, see https://pandas.pydata.org/pdeps/0004-consistent-to-datetime-parsing.html. You can safely remove this argument.
  s_dt = pd.to_datetime(s, errors="coerce", infer_datetime_format=True)
/tmp/ipython-input-869338356.py:26: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  s_dt = pd.to_datetime(s, errors="coerce", infer_datetime_format=True)
/tmp/ipython-input-869338356.py:26: UserWarning: The argument 'infer_datetime_format' is deprecated and will be removed in a future version. A strict version of it is now the default, see https://pandas.pydata.org/pdeps/0004-consistent-to-datetime-parsing.html. You can safely remove this argument.
  s_dt = pd.to_datetime(s, errors="coerce", infer_datetime_format=True)
/tmp/ipython-input-869338356.py:26: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  s_dt = pd.to_datetime(s, errors="coerce", infer_datetime_format=True)
/tmp/ipython-input-869338356.py:26: UserWarning: The argument 'infer_datetime_format' is deprecated and will be removed in a future version. A strict version of it is now the default, see https://pandas.pydata.org/pdeps/0004-consistent-to-datetime-parsing.html. You can safely remove this argument.
  s_dt = pd.to_datetime(s, errors="coerce", infer_datetime_format=True)
/tmp/ipython-input-869338356.py:26: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  s_dt = pd.to_datetime(s, errors="coerce", infer_datetime_format=True)
/tmp/ipython-input-869338356.py:26: UserWarning: The argument 'infer_datetime_format' is deprecated and will be removed in a future version. A strict version of it is now the default, see https://pandas.pydata.org/pdeps/0004-consistent-to-datetime-parsing.html. You can safely remove this argument.
  s_dt = pd.to_datetime(s, errors="coerce", infer_datetime_format=True)
/tmp/ipython-input-869338356.py:26: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  s_dt = pd.to_datetime(s, errors="coerce", infer_datetime_format=True)
/tmp/ipython-input-869338356.py:26: UserWarning: The argument 'infer_datetime_format' is deprecated and will be removed in a future version. A strict version of it is now the default, see https://pandas.pydata.org/pdeps/0004-consistent-to-datetime-parsing.html. You can safely remove this argument.
  s_dt = pd.to_datetime(s, errors="coerce", infer_datetime_format=True)
/tmp/ipython-input-869338356.py:26: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  s_dt = pd.to_datetime(s, errors="coerce", infer_datetime_format=True)

,column,orig_dtype,suggested_dtype,non_null,n_unique,pct_unique,reason
0,price,int64,int32,545,219,0.401835,downcast_integer
1,area,int64,int16,545,284,0.521101,downcast_integer
2,bedrooms,int64,int8,545,6,0.011009,downcast_integer
3,bathrooms,int64,int8,545,4,0.007339,downcast_integer
4,stories,int64,int8,545,4,0.007339,downcast_integer
5,mainroad,object,boolean,545,2,0.003670,bool_from_text
6,guestroom,object,boolean,545,2,0.003670,bool_from_text
7,basement,object,boolean,545,2,0.003670,bool_from_text
8,hotwaterheating,object,boolean,545,2,0.003670,bool_from_text
9,airconditioning,object,boolean,545,2,0.003670,bool_from_text
10,parking,int64,int8,545,4,0.007339,downcast_integer
11,prefarea,object,boolean,545,2,0.003670,bool_from_text
12,furnishingstatus,object,category,545,3,0.005505,low_cardinality

###🔄 Применение оптимизаций типов

In [22]:
df_opt = df.copy()
for _, row in report.iterrows():
    c = row["column"]
    target = row["suggested_dtype"]
    if target == row["orig_dtype"]:
        continue
    if target.startswith("int") or target.startswith("uint"):
        df_opt[c] = pd.to_numeric(df_opt[c], downcast="integer")
    elif target.startswith("float"):
        df_opt[c] = pd.to_numeric(df_opt[c], downcast="float")
    elif target == "boolean":
        try:
            df_opt[c] = df_opt[c].astype("boolean")
        except:
            vals = df_opt[c].astype(str).str.lower().str.strip()
            df_opt[c] = vals.replace({"true":True,"yes":True,"y":True,"1":True,"false":False,"no":False,"n":False,"0":False}).astype("boolean")
    elif target == "bool":
        df_opt[c] = df_opt[c].astype(bool)
    elif target == "datetime64[ns]":
        df_opt[c] = pd.to_datetime(df_opt[c], errors="coerce", infer_datetime_format=True)
    elif target == "category":
        df_opt[c] = df_opt[c].astype("category")

/tmp/ipython-input-2356280648.py:16: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_opt[c] = vals.replace({"true":True,"yes":True,"y":True,"1":True,"false":False,"no":False,"n":False,"0":False}).astype("boolean")
/tmp/ipython-input-2356280648.py:16: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_opt[c] = vals.replace({"true":True,"yes":True,"y":True,"1":True,"false":False,"no":False,"n":False,"0":False}).astype("boolean")
/tmp/ipython-input-2356280648.py:16: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_opt[c] = vals.replace({"true":True,"yes":True,"y":True,"1":True,"false":False,"no":False,"n":False,"0":False}).astype("boolean")
/tmp/ipython-input-2356280648.py:16: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_opt[c] = vals.replace({"true":True,"yes":True,"y":True,"1":True,"false":False,"no":False,"n":False,"0":False}).astype("boolean")
/tmp/ipython-input-2356280648.py:16: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_opt[c] = vals.replace({"true":True,"yes":True,"y":True,"1":True,"false":False,"no":False,"n":False,"0":False}).astype("boolean")
/tmp/ipython-input-2356280648.py:16: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_opt[c] = vals.replace({"true":True,"yes":True,"y":True,"1":True,"false":False,"no":False,"n":False,"0":False}).astype("boolean")

###⚖️ Сравнение памяти: до vs после

In [23]:
opt_mem_bytes = df_opt.memory_usage(deep=True).sum()
opt_mem_mb = opt_mem_bytes / (1024**2)
saving_mb = base_mem_mb - opt_mem_mb
saving_pct = (saving_mb / base_mem_mb * 100) if base_mem_mb else np.nan
pd.DataFrame({
    "metric":["memory_before_mb","memory_after_mb","saving_mb","saving_pct"],
    "value":[base_mem_mb, opt_mem_mb, saving_mb, saving_pct]
})

             metric      value
0  memory_before_mb   0.216717
1   memory_after_mb   0.012356
2         saving_mb   0.204361
3        saving_pct  94.298639

###🗂️ Изменения по столбцам

In [24]:
mem_before = df.memory_usage(index=False, deep=True)
mem_after = df_opt.memory_usage(index=False, deep=True)
delta = (mem_before - mem_after).sort_values(ascending=False)
changes = report.loc[report["orig_dtype"] != report["suggested_dtype"], ["column","orig_dtype","suggested_dtype","reason"]].set_index("column")
changes = changes.join(pd.DataFrame({"mem_before":mem_before, "mem_after":mem_after, "mem_saved":delta}))
changes.sort_values("mem_saved", ascending=False)

,orig_dtype,suggested_dtype,reason,mem_before,mem_after,mem_saved
column,,,,,,
furnishingstatus,object,category,low_cardinality,33101,834,32267
mainroad,object,boolean,bool_from_text,28263,1090,27173
basement,object,boolean,bool_from_text,27986,1090,26896
airconditioning,object,boolean,bool_from_text,27967,1090,26877
prefarea,object,boolean,bool_from_text,27923,1090,26833
guestroom,object,boolean,bool_from_text,27892,1090,26802
hotwaterheating,object,boolean,bool_from_text,27820,1090,26730
bedrooms,int64,int8,downcast_integer,4360,545,3815
stories,int64,int8,downcast_integer,4360,545,3815
bathrooms,int64,int8,downcast_integer,4360,545,3815
parking,int64,int8,downcast_integer,4360,545,3815
area,int64,int16,downcast_integer,4360,1090,3270
price,int64,int32,downcast_integer,4360,2180,2180

###✅ Проверка диапазонов и типов до/после

In [25]:
import pandas as pd, numpy as np
num_cols = ["price","area","bedrooms","bathrooms","stories","parking"]
def rng_tbl(d, cols):
    return pd.DataFrame({"min": d[cols].min(), "max": d[cols].max(), "dtype": d[cols].dtypes.astype(str)})
rng_before = rng_tbl(df, num_cols)
rng_after = rng_tbl(df_opt, num_cols).add_prefix("after_")
rng_compare = rng_before.join(rng_after)
rng_compare

               min       max  dtype  after_min  after_max after_dtype
price      1750000  13300000  int64    1750000   13300000       int32
area          1650     16200  int64       1650      16200       int16
bedrooms         1         6  int64          1          6        int8
bathrooms        1         4  int64          1          4        int8
stories          1         4  int64          1          4        int8
parking          0         3  int64          0          3        int8

###🧩 Фактические dtypes vs предложенные

In [26]:
actual_dtypes = df_opt.dtypes.astype(str)
applied = report[["column","orig_dtype","suggested_dtype"]].copy()
applied["actual_dtype"] = applied["column"].map(actual_dtypes)
applied

              column orig_dtype suggested_dtype actual_dtype
0              price      int64           int32        int32
1               area      int64           int16        int16
2           bedrooms      int64            int8         int8
3          bathrooms      int64            int8         int8
4            stories      int64            int8         int8
5           mainroad     object         boolean      boolean
6          guestroom     object         boolean      boolean
7           basement     object         boolean      boolean
8    hotwaterheating     object         boolean      boolean
9    airconditioning     object         boolean      boolean
10           parking      int64            int8         int8
11          prefarea     object         boolean      boolean
12  furnishingstatus     object        category     category

In [27]:
import pandas as pd, numpy as np

pd.DataFrame({"rows_before":[len(df)],"rows_after":[len(df_opt)],"cols_before":[df.shape[1]],"cols_after":[df_opt.shape[1]]})

   rows_before  rows_after  cols_before  cols_after
0          545         545           13          13